### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by aienabled** [Noesis/Managed#5]
Hi guys,
these two lines could be safely removed as there is no read access to this property (it's only assigned):
https://github.com/Noesis/Managed/blob/a8340f6b90240efae6ec8f91a303cd3585d6f0a0/Src/Noesis/Core/Src/Proxies/DependencyPropertyExtend.cs#L59

https://github.com/Noesis/Managed/blob/a8340f6b90240efae6ec8f91a303cd3585d6f0a0/Src/Noesis/Core/Src/Proxies/DependencyPropertyExtend.cs#L85

Regards!

**Comment by s-fernandez-v** [comment]
Yes, I already noticed that when integrating your DP resurrection code. Thanks anyway for pointing it out.
